config/dashboard/kustomization.yaml, config/dashboard/rbac.yaml, config/dashboard/service_account.yaml, hack/local-setup.sh
Add resources and automation to deploy the Kubernetes dashboard in local-setup
1. Run the local-setup
```sh
make local-setup
```
2. Verify the dashboard is deployed and follow the instructions to access it
3. Verify that the instructions are correct and the dashboard is accessible
=> Deploy Kubernetes dashboard in local-setup

.github/workflows/mctc-image.yaml
**Summary**
Adding workflow configurations file for building and publishing images from main and release branches to the Kuadrant quay.io repository
Successful build for reference: https://github.com/Kuadrant/multi-cluster-traffic-controller/actions/runs/4054326376/jobs/6976020870
Github Issue: https://github.com/Kuadrant/multi-cluster-traffic-controller/issues/13
=> Adding Github Action Workflow for building and pushing image to quay

Makefile, README.md, config/deploy/local/kustomization.yaml, config/deploy/local/manager_config_patch.yaml, config/manager/manager.yaml
Closes #19 
Add a kustomization that creates a ConfigMap and Secret from the local env files and mounts them in the controller Pod
> Ensure you have the correct values in the local env files `controller-config.env` and `aws-credentials.env`
1. Run local setup
```sh
make local-setup
```
2. Build and load the image
```sh
make docker-build
kind load docker-image controller:latest --name mctc-control-plane  --nodes mctc-control-plane-control-plane    
```
3. Deploy the controller
```sh
make deploy
```
4. Verify that the controller container runs correctly
=> Local deploy using env files

pkg/dns/service.go
=> Fix log statement

cmd/controller/main.go
Small change in the controller to allow a different cert-manager issuer to be used. This is required to make mgc unstable environment work with a Let's Encrypt issuer
1. Start the control plane, no workload clusters required
`make local-setup`
2. Deploy a custom cert-manager issuer
```
cat <<'EOF' | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
name: test-ca
spec:
selfSigned: {}
EOF
```
3. Deploy a GatewayClass
```
cat <<'EOF' | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
name: mctc-gw-istio-external-instance-per-cluster
spec:
controllerName: "kuadrant.io/mctc-gw-controller"
EOF
```
4. Run the controller using the Makefile, to ensure all is properly generated and installed. Once the controller is running …
=> Add option in the controller to configure the certificate provider

pkg/syncer/spec/controller.go, pkg/syncer/status/controller.go
=> no errors on delete, patch for status annotations

.github/workflows/ci.yaml
Adding our test suite `make test` to things that are run on each PR 
See the checks on the PR
=> GH-139 add tests ro GH workflow

docs/status_aggregation.md
Based on offline conversation about #127 
That PR can be updated based on the outcome of this proposal
=> Status aggregation proposal

docs/ocm-control-plane-walkthrough.md
updated ocm walkthough to take use from 1-2 clusters
=> walkthrough update

config/rbac/role.yaml, hack/make/controller.make, pkg/controllers/gateway/gateway_controller.go
fix permissions issues. Also removed the call to test for docker build as tests are not passing on this branch yet.
=> fix permissions issues

config/rbac/role.yaml, pkg/controllers/dnsrecord/dnsrecord_controller.go, pkg/controllers/gateway/gateway_controller.go, pkg/controllers/ratelimitpolicy/ratelimitpolicy_controller.go, pkg/dns/service.go, pkg/tls/service.go
1. Setup local environment
https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/milestone2_walkthrough.md 
1. Create a gateway
```
kubectl apply -n mctc-tenant -f ./gateway.yaml
```
2. Ensure DNS record and certs are created  
```
kubectl get dnsrecords -n multi-cluster-traffic-controller-system
kubectl get certs -n mctc-tenant 
kubectl get secrets -n mctc-tenant 
```
3. Delete the gateway 
```
kubectl delete gateway <gateway-name> -n mctc-tenant
```
4. Check that the DNS record and certs are removed
=> Gh 117 Cert and DNRecord deletion

pkg/controllers/gateway/gateway_controller.go
to verify run through the walkthrough and then delete the gateway. 
```
kubectl delete gateway prod-web -n multi-cluster-gateways
```
the dns and tls resources should also be gone
=> fix reference to gateway to ensure deletion of dns and certs

hack/local-setup.sh, hack/make/dependencies.make
* pin the version of clusteradm to 0.5.1
* pin the version of the ocm bunlde to 0.10.0
=> Pin clusteradm to 0.5.1 release and ocm bundle to 0.10.0

pkg/controllers/dnspolicy/suite_test.go
Remove reference to already removed crd
=> Fix dnspolicy suite_test

docs/proposals/status-aggregation.md
Accidentally removed from main.
=> Readd status aggregation proposal

.github/workflows/ci.yaml, hack/make/check.make, pkg/controllers/gateway/gateway_controller.go
- adds a new `verify-manifests` target to the makefile
- added this to our GH Action CI
fixes #236
=> make verify-manifests

docs/ocm-control-plane-walkthrough.md
Minor changes to OCM walkthrough:
- Additional requirements
- Added note on Kind issue
- Removed inline comment that gets included in ConfigMap
- Split input and output of shell commands
=> OCM walkthrough fixes

pkg/controllers/gateway/gateway_controller.go
These are the same:
* https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/pkg/controllers/gateway/gateway_controller.go#L423-L459 
* https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/pkg/controllers/gateway/gateway_controller.go#L463-L498
=> Remove extra placement and manifest work watches from gateway controller

pkg/controllers/gateway/suite_test.go, pkg/controllers/managedzone/suite_test.go
tests:
- managed zone can be created and deleted
- managed zone will enable a gateway using that host to be programmed
- managed zone will not enable a gateway using a different host
- managed zone will not enable a gateway in a different namespace, using it's host
=> adding managed zone integration tests

docs/how-to/ocm-control-plane-walkthrough.md
For some reason, I thought I'd done this before as part of a recent change. Anyway, doing this again. To get things working, setup an env-var like:
```
export MGC_SUB_DOMAIN=myapp.test.hcpapps.net # replace this
```
=> remove replace.this nonsense with env-vars

.vscode/settings.json
=> add new build tags for VSCode

pkg/controllers/gateway/cluster_eventhandler_test.go, pkg/controllers/gateway/gateway_controller_test.go, pkg/controllers/gateway/gatewayclass_controller_test.go, pkg/controllers/gateway/params_test.go, test/mockInterfaces.go, test/util/helper.go
Coverage change for the gateway package to 90.1%
Extended unit test coverage and created test files for booth controllers. 
No work on the integration right now. 
Verification is straightforward - tests are passing on the PR and coe looks neat and covers all the cases it should - PR is verified.
=> GH-114 increase coverage in gateway package

pkg/controllers/dnspolicy/dnspolicy_controller_test.go
Update the dnspolicy geo test to create a geo dns policy rather than updating an existing one. The update should work, but for whatever reason testenv doesn't alway appear to do it or the events are missed.
=> Fix flaky test

pkg/controllers/dnsrecord/dnsrecord_controller.go, pkg/dns/service.go
Fixes an issue where the dnsrecord can be updated unnecessary.
* Updates set endpoints to ensure the list is always the same (ordered by set id).
* Remove unnecessary dnsrecord update, check for status update and ignore conflict errors.
=> Fix dnsrecord updates

.github/workflows/ci.yaml, Makefile
=> Separate CI jobs for both unit and itegration tests

pkg/dns/service.go, pkg/dns/service_test.go
Update the logic for finding a matching managed zone for a given host to ensure that we do not return a ManagedZone that matches the host exactly. Currently records can only be created as subdomains of a ManagedZone and we do not support adding records for Apex domains.
closes #347
Temporary workaround to prevent nonsense records being created until we have [apex domain listener support. ](https://github.com/Kuadrant/multicluster-gateway-controller/issues/292)
**Verification**
* Create a ManagedZone and Gateway with the same dnsName/hostname. 
* No records should be  created
=> Handle apex domains being used as listener hosts

README.md, docs/how-to/managedZone.md, docs/how-to/ocm-control-plane-walkthrough.md, docs/how-to/ratelimiting-shared-redis.md, docs/how-to/submariner-poc-2-gateways-resiliency-walkthrough.md, docs/how-to/submariner-poc-hub-gateway-walkthrough.md, docs/how-to/template.md, docs/proposals/DNSPolicy.md, docs/proposals/DNSRecordStructure.md, docs/proposals/assets/multiple-dns-provider-support/azure/azure.md, docs/proposals/assets/multiple-dns-provider-support/google/google.md, docs/proposals/multiple-dns-provider-support.md, docs/proposals/status-aggregation.md
=> docs: minor typo fixes

config/cert-manager/kustomization.yaml
* Upgrades cert-manager to latest release
* Removes customizations that were required for kcp
=> Upgrade cert-manager

pkg/controllers/dnsrecord/dnsrecord_controller.go, pkg/dns/dns.go, pkg/dns/dns_test.go
=> DNSRecord AWS API Continuous loop

docs/getting-started.md, docs/how-to/ocm-control-plane-walkthrough.md
=> small spelling fixes

docs/how-to/ocm-control-plane-walkthrough.md, hack/quickstart-setup.sh
fixing link for curl to run the script. and removing the need to set context because it's set by the script at the end.
Also the metallb ip address wasn't updated.
I'm seeing some issues with the setup however which i'm investigating further
cc @philbrookes
=> docs and metalb update

docs/getting-started.md
Update the script link to main.
=> update script link

hack/.deployUtils
Small pr to add wait for deployments
=> waiting for deployments

.github/workflows/tools-image.yaml
GitHub Actions Workflow to build & push tools image for multiple platforms/architectures including:
- linux/amd64
- linux/arm64
Tested locally using https://github.com/nektos/act
=> Multi-platform tools image build

.github/workflows/addon-manger-image.yaml, Dockerfile
adds an image build for the add-on manager
=> add-on-manager workflow

docs/how-to/dnspolicy_basic.md
> Closes #424 
Add document describing how to define a basic DNSPolicy
* See document [here](https://github.com/Kuadrant/multicluster-gateway-controller/blob/90b8d2b815031bb1f35180f4268c68acbd3d8554/docs/how-to/dnspolicy_basic.md)
=> #424: DNSPolicy basic definition

docs/dns-health-checks.md
=> dns health check doc

docs/how-to/kuadrant-hub-install.md
=> #474: Use upstream Gateway API repo in guide

test/integration/dnsheathcheckprobe_controller_test.go, test/integration/dnspolicy_controller_test.go, test/integration/gateway_controller_test.go, test/integration/helper_test.go, test/integration/managedzone_controller_test.go, test/integration/tlspolicy_controller_test.go
=> Refactor tests to report errors clearly

docs/dnspolicy/dns-health-checks.md
Add missing `interval` field in `dns-health-checks.md`
=> New interval field

docs/getting-started.md, docs/installation/control-plane-installation.md
@philbrookes noticed some broken links.
=> fixing some broken links

hack/quickstart-setup.sh
Updates link to Multicluster Gateway setup guide in the quickstart script.
=> quickstart link fix

docs/getting-started.md, docs/installation/control-plane-installation.md
[update the hub install to allow for GCP user](https://github.com/Kuadrant/multicluster-gateway-controller/issues/493)
=> Gh 493 Update docs to include GCP

pkg/controllers/gateway/gateway_controller.go, pkg/controllers/gateway/gateway_controller_test.go, test/e2e/gateway_single_spoke_test.go
=> Ensure gateway not marked programmed if error with tls secrets

bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, config/manager/manager.yaml
=> Increase memory limit for mgc

docs/experimental/skupper-poc-2-gateways-resiliency-walkthrough.md
=> Add use case for skupper resiliency

hack/.deployUtils, hack/.quickstartEnv, hack/quickstart-setup.sh
Attempting to fix https://github.com/Kuadrant/multicluster-gateway-controller/issues/553
=> Fixes #553

docs/how-to/multicluster-gateways-walkthrough.md, docs/installation/service-protection-installation.md
Fixes for:
- #559 
- #560 
- #562
Related:
https://github.com/Kuadrant/docs.kuadrant.io/pull/22/files
=> #559 - fixes for the service protection installation guide & multicluster gateway walkthrough

docs/installation/control-plane-installation.md
> Closes #481 
Current doc is a bit confusing as it mentions `<snip>` when joining a spoke cluster to the hub, but it doesn't mention how to get that value.
Add a command that gets that value and improve formating
=> #481: Improve MGC existing clusters guide

docs/dnspolicy/dns-health-checks.md, docs/dnspolicy/dns-policy.md
Fixes #566 - adds additional docs for additionalHeadersRef
=> Fixes #566 - adds some additional docs around additionalHeadersRef

docs/gateways/define-and-place-a-gateway.md
keyboard mash got through pr my mistake
=> spelling mistake

pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/tlspolicy/tlspolicy_controller.go, test/integration/tlspolicy_controller_test.go
fixes #577 
[Add TLSPolicyAffected condition to target gateway](https://github.com/Kuadrant/multicluster-gateway-controller/commit/e749be150a95dec28062d7134d51499a7bfcfe99)
Adds the TLSPolicyAffected condition to the target gateway status
following the same logic that is currently implemented for [DNSPolicy](https://github.com/Kuadrant/multicluster-gateway-controller/pull/436).
[Update DNSPolicy](https://github.com/Kuadrant/multicluster-gateway-controller/commit/006fde78a196ff5b2ef2d2df225c78bd458112cb)
Updates the DNSPolicy reconciliation flow to update/remove (annotations)
and then update status as the last step during delete.
=> Add tlspolicy affected status

test/integration/tlspolicy_controller_test.go
closes #578 
Update TLS Policy HTTP tests, to expect certificate if TLS section is present.
=> update tests for HTTP expectations with TLS Policy

docs/how-to/multicluster-gateways-walkthrough.md
=> Remove reference to 2nd terminal

test/e2e/gateway_single_spoke_test.go, test/integration/helper_test.go, test/util/helper.go, test/util/suite_config.go, test/util/test_types.go
Adding automation for the following test cases https://github.com/Kuadrant/multicluster-gateway-controller/issues/592
Tests passing:
=> Gh 583 test

cmd/ocm/main.go
set the default channel when installing the manged addon to be stable
=> update the default channel to stable for install service protection

docs/tlspolicy/tls-policy.md
It was pointing to DNSPolicy instead of TLSPolicy
=> Update docs/tlspolicy/tls-policy.md link

docs/how-to/multicluster-gateways-walkthrough.md, docs/how-to/simple-ratelimitpolicy-for-app-developers.md
**Summary**
Made some minor updates and fixes to both the MGC and RateLimitPolicy walkthroughs based on recent run-through
=> MGC/RLP Walkthrough Updates

docs/installation/service-protection-installation.md
Relates to: https://github.com/Kuadrant/multicluster-gateway-controller/pull/600
=> fix service-protection-installation.md managedclusteraddon annotation

docs/gateways/define-and-place-a-gateway.md
clean up and improve gateway placement doc
=> minor tidy up

docs/dnspolicy/dns-provider.md, docs/dnspolicy/dnspolicy-quickstart.md, docs/installation/control-plane-installation.md, docs/managed-zone.md, docs/reference/managedzone.md
* Add a reference doc for the ManagedZone API
* Moved existing ManagedZone Overview doc out of dnspolicy
closes #682
=> docs: Add ManagedZone API reference doc

cmd/policy_controller/main.go, pkg/health/monitor.go, pkg/health/probeQueuer.go, pkg/health/queuedProbeWorker.go
Cherry-pick #706 into release-0.2 branch
=> Cherry-pick: Re-add health check components

docs/installation/control-plane-installation.md
update cert manager installation instructions. #722
=> update cert manager installation instructions

docs/how-to/api-walkthrough.md
Placeholder doc for landing docs issues from #740. I figure we land this now, and PR changes into this doc.
@david-martin @R-Lawton
=> Placeholder doc for #740

hack/upstream-api/local-setup-kind-api.sh, hack/upstream-api/local-setup-mgc-api.sh
Copied over the current version of the local setup scripts into a new folder as a starting point for us to contribute to
=> placeholder for scripts

.github/workflows/policy-controller-image.yaml
Updating the policy-controller image build to use the full commit sha
Resolves #759
=> Use full sha for policy-controller builds

README.md, docs/experimental/submariner-poc-2-gateways-resiliency-walkthrough.md, docs/experimental/submariner-poc-hub-gateway-walkthrough.md, docs/installation/control-plane-installation.md
Doc updates for https://github.com/Kuadrant/multicluster-gateway-controller/pull/785
=> docs: Remove policy-controller references

hack/.deployUtils, hack/.quickstartEnv
https://github.com/Kuadrant/kuadrant-operator/issues/459
This  will get the quick start back to a working state. However we need a better fix than sourcing these scripts from main of the gateway controller repo
=> fix for failing quick start
