main.go, pkg/controllers/traffic/traffic_controller.go, pkg/multiClusterWatch/main.go
This should ultimately be replaced with a service account client, but for now this will unblock development.
=> add control plane client to traffic controller

config/ingress-nginx/kustomization.yaml, samples/echo-service/echo.yaml
Disable the publish service feature which prevents the `reportNodeInternalIp` option working in local development. Without this option the internal cluster ip is used in the lb status preventing it being accessible outside of the cluster from the host.
```
$ make local-setup
$ kubectl apply -f samples/echo-service/echo.yaml 
service/echo created
deployment.apps/echo created
ingress.networking.k8s.io/echo created
$ kubectl get ingress echo -o json -w | jq .status.loadBalancer.ingress[0].ip
null
"172.18.0.2"
$ curl http://172.18.0.2
Request served by echo-7df5ffcf44-fnmzz
GET / HTTP/1.1
Host: 172.18.0.2
Accept: */*
User-Agent: curl/7.79.1
X-Forwarded-For: 172.18.0.1
X-Forwarded-Host: 172.18.0.2
X-Forwarded-Port: 80
X-Forwarded-Proto: http
X-Forwarded-Scheme: http
X-Real-Ip: 172.18.0.1 …
```
=> Update ingress nginx config

.github/workflows/ci.yaml, .golangci.yaml, Dockerfile, Makefile, hack/local-setup.sh, pkg/multiClusterWatch/main.go, pkg/traffic/ingress.go
Add the golangci-lint check to the Makefile, config for it, a github action to run it on PRs back to main, and fixes for current issues.
Adds a fix for the Dockerfile and removes external dns from the local setup.
GH Workflow tested here https://github.com/mikenairn/multi-cluster-traffic-controller/actions/runs/4014580657/jobs/6895274887
=> Add lint ci check

hack/.argocdUtils, hack/.kindUtils, hack/local-setup.sh
Adds the local-setup script the capability of creating workload clusters and registering them with argocd in the control-plane cluster. The number of workload clusters can be set with the environment variable `MCTC_WORKLOAD_CLUSTERS_COUNT`. If the variable is unset or empty only the control plane cluster will be created.
=> local-setup/multiple-workload-clusters

hack/.kindUtils
2 reasons:
- keep up to date
- fix issue below seen on some local dev environments
```
✓ Ensuring node image (kindest/node:v1.24.7) 🖼
✗ Preparing nodes 📦
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
make: *** [local-setup] Error 1
```
=> Update kindest node image to 1.26

README.md
Fix for `unknown option -addext` if an older version of openssl is used
=> Add openssl install instruction

Makefile, config/argocd/ingress-argocd-server.yaml, config/webhook-setup/control/ingress.yaml, config/webhook-setup/workload/webhook-configs.yaml, hack/.cleanupUtils, hack/.kindUtils, hack/local-cleanup.sh, hack/local-setup.sh
Currently, some of the configuration resources assume the IP of the control cluster being `172.17.0.2`. This is correct in the case of the local machine having no previous docker networks, as the creation of the kind clusters results in the creation of a bridge network and the IP range automatically assigned. However, in the scenario where there are other previous networks in the machine, the IP of the cluster will not match the IP specified in the resources.
As a first step to ensure consistency regardless of the current networks, modify the `local-setup` script to pre-create a network in the `172.32.0.0` subnet, and configure kind to use that network instead of automatically creating one. Update the resources that reference the control cluster IP to the new subnet
In order to verify …
=> Specify local docker network

Makefile, README.md, config/agent/agent.yaml, config/agent/kustomization.yaml, config/agent/role.yaml, config/agent/rolebinding.yaml, config/agent/secret.yaml, config/agent/serviceaccount.yaml
- Follow the steps in the readme to deploy the controller.
- Follow the steps in the readme to deploy the agent.
- Create sample application in workload cluster: `kubectl create -f samples/syncer/application.yaml`
- Watch logs of agent for: certificate secret in place for  host adding dns endpoints
- Curl the host.
=> deploy agent from kustomize yaml

config/kuadrant/kustomization.yaml, hack/local-setup.sh
1. Run make local setup 
`make local-setup MCTC_WORKLOAD_CLUSTERS_COUNT=<NUMBER_OF_CLUSTERS>`
Check  in the workload cluster that the following happens:
Note make sure you switch context to the right workload clusters
` kubectl config use-context kind-mctc-workload-1`
1. Namespace called `kuadrant-system` gets created
3. Operator gets installed
4. Kuadrant API CRDs should be available
`kubectl get crds | grep kuadrant`
```
authconfigs.authorino.kuadrant.io           2023-02-14T13:19:51Z
authorinos.operator.authorino.kuadrant.io   2023-02-14T13:19:51Z
authpolicies.kuadrant.io                    2023-02-14T13:19:47Z
kuadrants.kuadrant.io                       2023-02-14T13:19:47Z
limitadors.limitador.kuadrant.io            2023-02-14T13:19:51Z
ratelimitpolicies.kuadrant.io …
```
=> Kuadrant operator

.github/workflows/mctc-image.yaml
The Dockerfile now contains build targets for both the controller and the agent, so we need to specify which target we want to build in the build action (right now it's building just the last one, which happens to be the agent). 'redhat-actions/buildah-build@v2' doesn't have support for the 'target' paremeter, so I have switched to the
'docker/build-push-action@v4' action instead. It required quite a few changes as the format of the parameters is different.
I could easily add builds for the agent to this same workflo, but it might be better to have a different workflow to have separate success/failure notifications for both images, wdyt?
Check the test run [here](https://github.com/Kuadrant/multi-cluster-traffic-controller/actions/runs/4203440226/jobs/7292834721)
=> Fix the controller image build in GH actions

config/metallb/kustomization.yaml, hack/local-setup.sh
This change enables Services of type `LoadBalancer` in a local development environment to be assigned an IP Address.
This is required for local istio Gateways running in workload clusters, as it uses a Service of type `LoadBalancer`
To verify, bring up a local development environment with 2 workload clusters (2 to verify the IPAddressPool subnet works for each new workload cluster)
```
MCTC_WORKLOAD_CLUSTERS_COUNT=2 make local-setup
```
Deploy a sample app to both workload clusters, including a Service of type `LoadBalancer`
```
kubectl --context kind-mctc-workload-1 apply -n default -f https://gist.githubusercontent.com/david-martin/d30bd544436be7244d8ecaefc848cfd7/raw/ca59823ac856e6a3815c42726c0c556a8cd586f0/sample_app_with_loadbalancer.yaml
kubectl --context kind-mctc-workload-2 apply …
```
=> Add MetalLB to local workload clusters for Services of type LoadBalancer

README.md
Correct the name of the `controller-config` env file referenced in the README
Related to #62
=> Correct name of env file

config/istio/istiod/configmap.yaml, config/istio/istiod/kustomization.yaml, config/samples/gateway_istio.yaml
This fixes an istiod configuration issue that results in an istio gateway not being usable.
To reproduce the issue on `main`, start a local dev environment with 1 workload cluster:
```
MCTC_WORKLOAD_CLUSTERS_COUNT=1 make local-setup
```
Then create an istio Gateway resource in the workload cluster
```
kubectl --context kind-mctc-workload-1 apply -n istio-system -f https://raw.githubusercontent.com/david-martin/multi-cluster-traffic-controller/istiod_config/config/samples/gateway_istio.yaml
```
Check the logs for the below lines that indicate the configuration issue
```
kubectl --context kind-mctc-workload-1 -n istio-system logs -f $(kubectl --context kind-mctc-workload-1 -n istio-system get po -l istio=ingressgateway -o name) | grep -i xds
2023-02-17T10:53:47.731173Z	info	xdsproxy …
```
=> Patch istiod config for local environment use

Makefile, config/webhook-setup/proxy/deployment.yaml, config/webhook-setup/proxy/kustomization.yaml, config/webhook-setup/proxy/namespace.yaml, config/webhook-setup/proxy/nginx.conf, config/webhook-setup/proxy/service.yaml, hack/local-setup.sh
> Closes #32 
Add a command to deploy a simple proxy in the control cluster, which redirects requests to the local host, and is exposed as the webhook endpoint. This allows the workload clusters to maintain the same webhook configuration while running the controller in the localhost
Follow the instructions in the [README](https://github.com/Kuadrant/multi-cluster-traffic-controller/blob/4b9e56c32526ee5ca127a9b8711aaca774214d98/README.md#2-running-locally) to run the controller locally and ensure the webhooks are reachable
=> GH-32: Add proxy to enable webhooks when running locally

Makefile, README.md
* Fix dev-tls so it generates a cert for the control cluster (172.32.0.2) and not the host (172.32.0.1). Broken by me in https://github.com/Kuadrant/multi-cluster-traffic-controller/pull/87
* Fix run-agent so it looks in the correct ns for control cluster config secret
=> Fix make targets for local dev

Dockerfile, Makefile, cmd/agent/main.go, cmd/controller/main.go, cmd/syncer/main.go, config/syncer/kustomization.yaml, config/syncer/role.yaml, config/syncer/rolebinding.yaml, config/syncer/serviceaccount.yaml, config/syncer/syncer.yaml, hack/.argocdUtils, hack/.clusterUtils, hack/gen-agent-secret.sh, hack/local-setup.sh, hack/make/agent.make, hack/make/controller.make, hack/make/dependencies.make, hack/make/syncer.make, pkg/_internal/clusterSecret/client.go, pkg/syncer/spec/controller.go, pkg/syncer/sync.go
- `export LOCAL_ACCESS="true"`
- run a fresh: `make local-setup MCTC_WORKLOAD_CLUSTERS_COUNT=1`
- open 3 terminals
- in terminal 1 target the control plane: `export KUBECONFIG=./tmp/kubeconfigs/mctc-control-plane.kubeconfig`
- in terminal 2 and 3 target the workload cluster: `export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig`
- in terminal 2, run: `make run-syncer`
- in terminal 1: `kubectl create -f config/samples/gateway.yaml`
- **expectation:** nothing should happen
- in terminal 1: edit the gateway and add the annotation: `mctc-sync-agent/kind-mctc-workload-1: "true"`
- there should be activity in terminal 2
- in terminal 3: `kubectl get gateway example-gateway -n mctc-downstream -o yaml`
- **expectation:** The  gateway should be present in the downstream cluster
- in …
=> dumb sync - spec

hack/.kindUtils
local-setup is failing if `kind` binary is not in the user's PATH.
```
❯ make local-setup
test -s /home/roi/github.com/kuadrant/multi-cluster-traffic-controller/bin/kustomize || { curl -Ss "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 4.5.4 /home/roi/github.com/kuadrant/multi-cluster-traffic-controller/bin; }
test -s /home/roi/github.com/kuadrant/multi-cluster-traffic-controller/bin/yq || GOBIN=/home/roi/github.com/kuadrant/multi-cluster-traffic-controller/bin go install github.com/mikefarah/yq/v4@v4.30.8
./hack/local-setup.sh
No kind clusters found.
Deleting mctc network
mctc
7e3286119652344fbd01dc8b59d3c16e03e16ce218311d0c8ef9d67a1006960b
Creating cluster "mctc-control-plane" ...
WARNING: Overriding docker network due to …
```
=> Use project binary for kind

cmd/syncer/main.go, config/syncer/role.yaml, config/syncer/syncer.yaml, hack/make/syncer.make, pkg/syncer/spec/controller.go, pkg/syncer/sync.go
The manager from kubebuilder was exiting immediately because as far as it was concerned it had no tasks to run. This PR converts the syncer informers to run as a mgr task so that the manager does not exit too early.
- `export LOCAL_ACCESS="true"`
- run a fresh: `make local-setup MCTC_WORKLOAD_CLUSTERS_COUNT=1`
- open 3 terminals
- in terminal 1 target the control plane: `export KUBECONFIG=./tmp/kubeconfigs/mctc-control-plane.kubeconfig`
- in terminal 2 and 3 target the workload cluster: `export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig`
- in terminal 2, run: 
- `make kind-load-syncer`
- `make deploy-syncer`
- in terminal 1: `kubectl create -f config/samples/gateway.yaml`
- **expectation:** nothing should happen
- in terminal 1: edit the gateway and add the annotation: …
=> Deploy dumb syncer

Makefile, OWNERS, hack/make/check.make
Adding:
* `make code/fix` - to format and fix the code 
* `make code/check` to enable prow ensuring the code in PR is formatted 
* `make vendor/fix` to clean/fix up vendors 
* `make vendor/check` to enable prow ensuring vendors are fine 
1. Ensure commands are working as expected 
2. Ensure vendor changes in this PR aren't causing any trouble.
=> HCG-171 add make targets for prow

cmd/syncer/main.go, pkg/syncer/spec/controller.go, pkg/syncer/status/controller.go, pkg/syncer/sync.go
Adds a spec syncer which will sync spec from upstream to downstream.
This also adds an argument to specify which namespace in the control plane to sync spec from and status to.
The code is not ideal, and I will be submitting a PR to improve it, I just want to get a working POC in, so that MS2 is not blocked.
##Verification
`make local-setup MCTC_WORKLOAD_CLUSTERS_COUNT=1`
`make kind-load-syncer`
`export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig`
`make deploy-syncer`
`export KUBECONFIG=./tmp/kubeconfigs/mctc-control-plane.kubeconfig`
`kubectl create namespace mctc-tenant`
`kubectl create -f config/samples/gateway.yaml -n mctc-tenant`
`kubectl annotate gateway example-gateway mctc-sync-agent/all=true -n mctc-tenant`
`kubectl get gateway example-gateway -n mctc-tenant -o yaml` …
=> sync status back to control plane

config/syncer/syncer.yaml, hack/make/syncer.make, pkg/syncer/spec/controller.go, pkg/syncer/sync.go
allow multiple resources to sync
allow core resources to sync
##verify
```
make local-setup MCTC_WORKLOAD_CLUSTERS_COUNT=1
export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig
make kind-load-syncer
make deploy-syncer
export KUBECONFIG=./tmp/kubeconfigs/mctc-control-plane.kubeconfig
kubectl create ns mctc-tenant
kubectl create -f config/samples/secret.yaml -n mctc-tenant
kubectl annotate secret cluster1 mctc-sync-agent/all=true -n mctc-tenant
export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig
kubectl get secret cluster1 -n mctc-downstream -o yaml
```
=> Sync agent multi resources

config/syncer-control/kustomization.yaml, config/syncer-control/role.yaml, config/syncer-control/rolebinding.yaml, config/syncer-control/serviceaccount.yaml, config/syncer/.gitignore, config/syncer/kustomization.yaml, config/syncer/syncer_parameter_patch.json, hack/.clusterUtils, hack/.kindUtils, hack/register-cluster.sh
> Closes #44 
Cluster registration script
1. Run local-setup with only the control cluster
```sh
make local-setup
```
1. Create the tenant namespace in the control cluster
```sh
kubectl create namespace my-tenant
```
1. Create the tenant cluster
```sh
source hack/.setupEnv
source hack/.kindUtils
kindCreateCluster tenant-cluster 9091 8446
```
1. Install Gateway API in the tenant cluster
```sh
export KUBECONFIG=$(pwd)/tmp/kubeconfigs/tenant-cluster.kubeconfig
./bin/kustomize build config/gateway-api | kubectl apply -f -
```
1. Run the register cluster script
```sh
export KUBECONFIG=$(pwd)/tmp/kubeconfigs/mctc-control-plane.kubeconfig
kubectl config use-context kind-mctc-control-plane
./hack/register-cluster.sh $(pwd)/tmp/kubeconfigs/internal/mctc-control-plane.kubeconfig …
```
=> #44: Cluster registration

.gitignore, cmd/controller/main.go, config/cert-manager/crd/v1.7.1/cert-manager.crds.yaml, config/samples/echo_httproute.yaml, config/samples/gateway.yaml, pkg/_internal/conditions/conditions.go, pkg/admission/traffic/webhook_handler.go, pkg/controllers/gateway/gateway_controller.go, pkg/controllers/gateway/gatewayclass_controller.go, pkg/controllers/gateway/suite_test.go, pkg/controllers/ingress/ingress.go, pkg/dns/service.go, pkg/syncer/spec/controller.go, pkg/tls/service.go, pkg/traffic/gateway.go, pkg/traffic/ingress.go, pkg/traffic/traffic.go
closes #45, closes #46 
*Steps to verify locally using Route53*
**IMPORTANT** These steps assume your local ./aws-credentials.env file has all values (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_REGION`) set and ./controller-config.env file has the right values for `ZONE_ROOT_DOMAIN` and `AWS_DNS_PUBLIC_ZONE_ID` that match dev.hcpapps.net.
**IMPORTANT** Change the hostname in the Gateway and HttpRoute to avoid reusing `myapp.dev.hcpapps.net` e.g. Use `<myname>.dev.hcpapps.net`
```
cp config/samples/gateway.yaml ./gateway.yaml
cp config/samples/echo_httproute.yaml ./echo_httproute.yaml
vi gateway.yaml
vi echo_httproute.yaml
```
**Terminal 1** Local setup & start the controller in the control plane cluster
```
MCTC_WORKLOAD_CLUSTERS_COUNT=1 make local-setup
(export $(cat …
```
=> Reconcile Istio Gateway

.gitignore, config/syncer/kustomization.yaml, config/syncer/syncer_parameter_patch.json, docs/milestone2_application.yaml, docs/milestone2_gateway.yaml, docs/milestone2_ratelimitpolicy.yaml, docs/milestone2_walkthrough.md
Depends on #84 
Will rebase when that merges.
This PR adds a completely standalone walkthrough for milestone 2.
It probably make sense to tag main as `milestone-2` after this merges for easier linking to the walkthrough.
It should be possible for anyone to follow the walkthrough doc, having satisfied the prerequisites, and hit all of the goals called out in the doc.
I've deliberately left out any steps about custom ManagedZones as this may overcomplicate the walkthrough given that you'll need AWS route53 credentials and a hosted zone anyways to deploy the controller. I think that can be covered in separate docs.
=> M2 walkthrough

pkg/controllers/gateway/gateway_controller.go, pkg/controllers/ingress/ingress.go, pkg/dns/service.go
closes #111 
Updates the gateway reconciler to build up a list of managed hosts which includes a reference to the managed zone which can service it, and the DNSRecord that will exist or just have been created for it.  Later in the reconciliation when adding endpoints, we can now explicitly tell it what DNSRecord to add the endpoints to for each managed host.
The reconcilation logic between ingress and gateways is currently quite different. Ingresses expects a single host to be generated for a suitable manged zone and gateways do a lookup of multiple associated hosts for a managed zone capable of serving each. To make things easier this PR separates the logic for the two inside the dns service since trying to make it work for both is counterintuitive as we will more than likley remove the …
=> Improve MZ and record lookup for gateway reconciles

pkg/controllers/gateway/gateway_controller.go
Ignore not found errors when checking for existing DNSRecord.
Related https://github.com/Kuadrant/multi-cluster-traffic-controller/pull/120
=> Fix DNSRecord lookup in gateway reconcile

Dockerfile, cmd/syncer/main.go, config/samples/gateway.yaml, config/syncer/kustomization.yaml, hack/.argocdUtils, hack/.clusterUtils, hack/make/syncer.make, pkg/_internal/metadata/annotations.go, pkg/syncer/mutator/annotationCleaner.go, pkg/syncer/mutator/jsonpatch.go, pkg/syncer/spec/controller.go, pkg/syncer/status/controller.go, pkg/syncer/sync.go
Primary changes:
- Implements specdiff annotations
- Removes MCTC annotations from downstream resources
- MCTC_WORKLOAD_CLUSTERS_COUNT=1 make local-setup
- export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig
- make kind-load-syncer
- make deploy-syncer
- export KUBECONFIG=./tmp/kubeconfigs/mctc-control-plane.kubeconfig
- kubectl create namespace mctc-tenant
- kubectl apply -n mctc-tenant -f ./config/samples/gateway.yaml
- export KUBECONFIG=./tmp/kubeconfigs/mctc-workload-1.kubeconfig
- kubectl get gateways example-gateway -n mctc-downstream -o yaml
- see that the name of the listener is 'test' and the gatewayClassName is 'boo'
- see that no mctc specific annotations exist
=> Sync agent json patches

pkg/_internal/clusterSecret/util.go, pkg/_internal/slice/slice.go, pkg/controllers/gateway/cluster_eventhandler.go, pkg/controllers/gateway/cluster_eventhandler_test.go, pkg/controllers/gateway/gateway_controller.go
> Closes #85
Add a watch for secrets in the Gateway controller that will enqueue gateways if there's a change in the related cluster secret
1. For testing purposes, as #52 is not done, update [this line of code](https://github.com/david-martin/multi-cluster-traffic-controller/blob/8bb9849ad642abdc847d5995ea34f3d07a187b17/pkg/controllers/gateway/gateway_controller.go#L337) to the following:
```go
return []string{"mctc-workload-1"}
```
1. Run local-setup and start the controller
1. Create a sample gateway
1. Update the secret for the workload cluster
1. Verify that the sample gateway is reconciled
=> #85: Reconcile Gateway from watching cluster secret

cmd/syncer/main.go, pkg/_internal/env/env.go, pkg/_internal/env/env_test.go, pkg/syncer/spec/suite_test.go, pkg/syncer/status/suite_test.go, pkg/syncer/sync.go
two fixes:
- Default downstream namespace if none provided
- Status syncer no longer expects the syncer annotation on downstream resources
ping @mikenairn @david-martin
=> Syncer fix

.github/workflows/controller-image.yaml
It's basically the same job that we had running in the kcp-glbc repo.
An example run of the job can be seen [here](https://github.com/Kuadrant/multicluster-gateway-controller/actions/runs/4573768079) which created commit https://github.com/redhat-cps/glbc-deployments/commit/e4b4a77f14d996582bf07778be61b8c02106c81b.
=> GH-15 add job to deploy latest controller image to unstable environment

config/kuadrant/cr/kuadrant.yaml, config/kuadrant/cr/kustomization.yaml, hack/.argocdUtils, hack/.clusterUtils, hack/local-setup.sh, hack/make/syncer.make
Local setup changes
- Allow overriding metrics and health ports on the `make run-syncer` command so you can run more than one locally:
```
METRICS_PORT=8088 HEALTH_PORT=8089 make run-syncer
```
- Remove kind from names in cluster secrets and make the cluster name consistent accross the control and data plane.
```
kubectl get secret mctc-workload-1 -n argocd --context kind-mctc-control-plane -o jsonpath="{.data.name}" | base64 --decode && echo ""
mctc-workload-1
kubectl get secret control-plane-cluster -n mctc-system --context kind-mctc-workload-1 -o jsonpath="{.data.name}" | base64 --decode && echo ""
mctc-workload-1
```
- Add kuadrant CR to local-setup
=> Local setup updates

config/samples/gatewayclass.yaml, config/samples/gatewayclass_params.json, hack/local-setup.sh, pkg/controllers/gateway/gateway_controller.go, pkg/controllers/gateway/gatewayclass_controller.go, pkg/controllers/gateway/params.go, pkg/controllers/gateway/params_test.go
> Closes #118 
Ability to get parameters from a resourced referenced in the `parametersRef` of the GatewayClass
As the parameters are currently not used, in order to verify this functionality, ensure that the adequate status condition is reconciled when the `parametersRef` is misconfigured.
1. Start the local development clusters
```sh
MCTC_WORKLOAD_CLUSTERS_COUNT=1 make local-setup
```
3. Run the controller
```sh
(export $(cat ./controller-config.env | xargs) && export $(cat ./aws-credentials.env | xargs) && make build-controller install run-controller)
```
1. Create the parameters ConfigMap
```sh
kubectl create configmap gateway-params --from-file=params=config/samples/gatewayclass_params.json -n multi-cluster-traffic-controller-system
```
5. Create the GatewayClass
```yaml
apiVersion: …
```
=> #118: Ability to handle parameters in GatewayClass

pkg/traffic/gateway.go, pkg/traffic/gateway_test.go
This PR includes the changes from #161 and adds a fix to detect istio's incorrect reporting of AWS ELB hosnames as `Type: IPAddress` in the status of istio managed Gateways.
Supersedes #161 and fixes #160 .
/kind bug
/cc @mikenairn 
/cc @maleck13
=> Fix gateway get dns targets

README.md, hack/local-setup.sh
Use `${CLUSTERADM_BIN}` throughout `local-setup.sh`
Fixes:
```
secret/mctc-aws-credentials created
installing the hub cluster in kind-(mctc-control-plane)
./hack/local-setup.sh: line 224: clusteradm: command not found
make: *** [local-setup] Error 127
```
=> Clusteradm path

hack/local-setup.sh
Fixes #101 
Add a `kubectl wait` command after deploying the Kubernetes dashboard in order to make sure the dashboard is running before continuing
=> #101 Wait for dashboard deployment

hack/local-setup.sh
Make sure the counter expression never has a value of 0.
see https://unix.stackexchange.com/questions/146773/why-bash-increment-n-0n-return-error/146777
Alternatively just setting the initial value of the counters to 1 would also likely work
=> Fix local-setup on linux

docs/ocm-control-plane-walkthrough.md
Some edits to add extra clarity to the OCM PoC setup guide, including:
- Refs to which terminal to use to run various setup commands
- Markdown syntax highlighting for code blocks
I'll hold off on a merge until https://github.com/Kuadrant/multicluster-gateway-controller/pull/232 lands, as that known issue which I've removed a ref to won't be fixed until that is merged.
=> docs: Update the OCM walkthrough for clarity

Makefile, pkg/_internal/env/env_test.go, pkg/_internal/metadata/annotations_test.go, pkg/_internal/metadata/finalizers_test.go, pkg/_internal/metadata/labels_test.go, pkg/_internal/sync/patch_test.go, pkg/controllers/dnspolicy/suite_test.go, pkg/controllers/dnsrecord/suite_test.go, pkg/controllers/gateway/cluster_eventhandler_test.go, pkg/controllers/gateway/params_test.go, pkg/controllers/gateway/suite_test.go, pkg/dns/aws/aws_test.go, pkg/dns/aws/health_test.go, pkg/dns/service_test.go, pkg/placement/placement_test.go, pkg/syncer/mutator/annotationCleaner_test.go, pkg/syncer/mutator/jsonpatch_test.go, pkg/syncer/spec/suite_test.go, pkg/syncer/status/suite_test.go, pkg/traffic/gateway_test.go
Add unit and integration buid tags to all test files and adds 2 new make targets to run the unit (make test-unit) and integration (make test-integration) tests. Running the integration tests will run it with the ginkgo verbose flag which fails when you try and use it on normal unit test files.
=> Add test build tags (unit and integration)

pkg/dns/service.go, pkg/dns/service_test.go
Increasing test coverage for the DNS package. 
Touched only the `service.go`. 
The `health` controller doesn't have anything in there that would not be handy to test by integration suite. 
`target`, `hostresolv` and `dns` don't have much to unit test in them. 
The files in the AWS subpackage - not sure if it makes sense to also unit test them.
=> GH-214 dns package unit coverage

hack/make/controller.make, pkg/_internal/gracePeriod/gracePeriod.go, pkg/_internal/gracePeriod/gracePeriod_test.go, pkg/_internal/metadata/annotations.go, pkg/_internal/policy/policy.go, pkg/_internal/policy/policy_test.go, pkg/apis/v1alpha1/dnspolicy_types.go, pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/gateway/gateway_controller.go, pkg/dns/dns.go, pkg/dns/service.go, pkg/placement/ocm.go, pkg/placement/placement_test.go
- Allow a grace period of 600 seconds when descheduling a gateway from a spoke cluster
- Update e2e tests
- Add new unit tests
- Few small refactoring changes 
- Avoiding messy imports
- Straightening out some of the managed zone matching logic
follow [walkthrough](https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/how-to/ocm-control-plane-walkthrough.md) until gateway is replicated to the spoke cluster.
- deschedule the cluster:
- kubectl label --overwrite managedcluster kind-mgc-control-plane ingress-cluster=false
- See gateway and manifestworks still exist: 
- kubectl get gateway -A
- kubectl get manifestworks -A
- Wait 10 minutes
- See gateway and manifestworks are deleted
=> add grace period to descheduled gateways

.github/workflows/ci-e2e.yaml, .github/workflows/ci.yaml, Dockerfile, hack/make/dependencies.make
Adds new job to the CI workflow to run the e2e tests against the local-setup environment. I also updated the go-setup to action to v4 as later versions have built-in caching.
The e2e suite takes a while to complete, something in the order of 12-14 minutes, with most of the time being spent on the local-setup script itself and the tests taking just about a couple of minutes. We might need to consider some improvements to the local-setup script to try and reduce this time (hiding the installation of some things like argocd and k8s-dashboard behind flags, some parallelization, etc).
=> Add e2e test to ci

config/rbac/role.yaml, hack/make/controller.make, pkg/controllers/dnspolicy/dnspolicy_controller.go
Adds the missing RBAC to allow watching OCM ManagedCluster resources from the DNSPolicy reconciler.
Should have been added as part of https://github.com/Kuadrant/multicluster-gateway-controller/pull/293
=> Add missing rbac

.github/workflows/ci-e2e.yaml
Some improvements/fixes to the E2E CI workflow:
* Add the contributor "role" to those that don't require approval. I have reviewed the PRs after the e2e workflow was in place and have seen that even though we are all members of the Kuadrant org, in the event for the pull_request we are marked as contributors.
* Rename the GH environments so they are clearly identified as part of the e2e workflow
* Merge all jobs into one using several steps instead
/cc @david-martin
=> Improvements/fixes to the E2E CI workflow

README.md, hack/make/dependencies.make
There's no issue for this. Should I create one?
Spotted a small error `ls: /Users/lfitzger/MCG/multicluster-gateway-controller/bin/operator-sdk: No such file or directory` when running any of the make commands before the operator-sdk one which prompted to me to make one change which resulted in a few more inside the depencies.make file.
Running `make dependencies` should result in the following binaries installed into bin directory
clusteradm     controller-gen ginkgo         helm           istioctl       kind           kustomize      operator-sdk   setup-envtest  subctl         yq
and a successful message whether you previously had them installed or not.
=> dependency pre-req and some associated makefile updates

config/crd/bases/kuadrant.io_managedzones.yaml, pkg/apis/v1alpha1/managedzone_types.go, pkg/controllers/managedzone/suite_test.go
Fixes https://github.com/Kuadrant/multicluster-gateway-controller/issues/323
Adds hostname validation to `domainName` in the `managedzone` CR
Regex:
https://regex101.com/r/ZIYOaE/1
=> Domain name crd validation

Makefile
The make fmt command was using the wrong path causing odd issues.
=> Fix make fmt

pkg/dns/service.go, pkg/dns/service_test.go
closes #328  
Fixes an issue where a DNSRecord could get created with some endpoints, but have no actual targets for them to point to.
If we have cluster targets that have no addresses when building up our list of Endpoints for the DNSRecord they are now completely ignored and no CNAME or A records related to that cluster are created.  If no targets in a geo have valid addresses, the geo is ignored and no records created for it.  If no records can be created for any targets (no targets have addresses), nothing is created and an empty endpoints list returned.
=> Fix dnsrecord when no addresses in any targets

docs/how-to/ocm-control-plane-walkthrough.md
Stepping through the OCM walkthrough today to get things back up and running, I ran into some issues:
* The `./controller-config.env` you end up with as part of the walkthrough is malforme
* Created a related issue here https://github.com/Kuadrant/multicluster-gateway-controller/issues/323 to not allow malformed domain names for `managezone`'s
* Added a `kubectl patch` for the numberOfClusters command later in the walkthrough
=> Fixing some walkthrough docs

pkg/_internal/gracePeriod/gracePeriod.go, pkg/_internal/gracePeriod/gracePeriod_test.go, pkg/controllers/dnspolicy/cluster_eventmapper.go, pkg/placement/ocm.go
Fixes #303
When a ManagedCluster is deleted, don't attempt to update the DNSPolicy straight away.
Instead, reconcile the Gateway first, which will trigger a DNSPolicy reconcile if there are any changes related to placement changes e.g.
IPAddresses changing.
When a ManagedCluster is deleted, don't wait for the grace period before deleting a Gateway (via ManifestWork).
Instead, delete the ManifestWork straight away.
Due to a known issue in OCM, https://github.com/open-cluster-management-io/ocm/issues/140 the ManifestWork is not removed after the deletionTimestamp is added in this sceanrio.
To allow for this, the gateway placement logic will filter out any ManifestWork resources that have a deletionTimestamp set.
To verify:
* Follow through the full ocm walkthrough
* Delete 1 of the …
=> Handle MangedCluster delete events

docs/dns-policy.md, docs/how-to/ocm-control-plane-walkthrough.md, docs/how-to/submariner-poc-2-gateways-resiliency-walkthrough.md, docs/how-to/submariner-poc-hub-gateway-walkthrough.md, go.mod, go.sum, pkg/controllers/dnspolicy/dns_helper.go, pkg/controllers/dnspolicy/dns_helper_test.go, pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go, pkg/controllers/gateway/gateway_controller.go, test/e2e/gateway_single_spoke_test.go, test/integration/dnspolicy_controller_test.go
/closes #359
Removes the default DNSPolicy creation from the gateway controller.
Update labelling of resources created by the DNSPolicy. Brings it in-line with how the other kuadrant polices work, and makes it easier to find resources created by a policy.
```bash
kubectl get dnsrecords -A --show-labels
NAMESPACE                NAME                   READY   LABELS
multi-cluster-gateways   myapp.mn.hcpapps.net   True    gateway-namespace=multi-cluster-gateways,gateway=prod-web,kuadrant.io/dnspolicy-namespace=multi-cluster-gateways,kuadrant.io/dnspolicy=prod-web
```
=> DNSPolicy improve default behaviour

config/istio/istio-namespace.yaml, config/istio/kustomization.yaml, hack/quickstart-setup.sh
Related to https://github.com/Kuadrant/multicluster-gateway-controller/issues/286
Without the istio-system namespace the kustomize wont fail but the istio components don't get deployed
Adding a check to the script as well so that the script would wait for deployments both for the operator and for the istio deployment itself. 
**Verification** 
can be done by running the script in it's existing state.
verify that no istio-system namespace is present.
also following the steps in the ocm-walkthrough will result in the gateways being stuck in this stage
```oc get gateway -A
NAMESPACE                         NAME       CLASS                                                 ADDRESS   PROGRAMMED   AGE
kuadrant-multi-cluster-gateways   prod-web   istio …
```
=> add istio system namespace

config/crd/bases/kuadrant.io_dnshealthcheckprobes.yaml, config/crd/bases/kuadrant.io_dnspolicies.yaml, pkg/apis/v1alpha1/dnshealthcheckprobe_types.go, pkg/apis/v1alpha1/dnspolicy_types.go, pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks.go, pkg/controllers/gateway/gateway_controller.go, pkg/health/probeQueuer.go, pkg/health/queuedProbeWorker.go
Fix health probes for TLS endpoints and allow ignoring bad certificates.
=> Health Probe fixes for TLS

config/default/kustomization.yaml, config/default/manager_metrics_patch.yaml, config/prometheus-for-federation/grafana-dashboard-mgc-metrics.json, config/prometheus-for-federation/grafana_deployment_patch.yaml, config/prometheus-for-federation/kustomization.yaml, config/prometheus/monitor.yaml, config/prometheus/service.yaml
Closes #308 
Run `make local-setup OCM_SINGLE=true METRICS_FEDERATION=true MGC_WORKLOAD_CLUSTERS_COUNT=1` and `make build-controller kind-load-controller deploy-controller METRICS=true`
The dashboard can be found on the Default dashboard page named: `MGC SRE Dashboard`
- Are there any specific visualizations that should be prioritized on the dashboard? (e.g., graphs, tables, gauges, heatmaps)
- Are there additional metrics or data sources that should be included in this dashboard?
- Would it be beneficial to incorporate more variables to allow users to filter and customize the dashboard's data dynamically?
- Are there specific variables that should be used?
=> Add mgc metric dashboard

pkg/controllers/dnshealthcheckprobe/dnshealthcheckprobe_controller.go, pkg/controllers/dnspolicy/dns_helper.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks.go, pkg/health/metrics.go
> Closes #314 
Create and expose a metric that counts the number of health check failures per probe
1. Run the local-setup
```sh
make local-setup OCM_SINGLE=true MCTC_WORKLOAD_CLUSTERS_COUNT=1
```
3. Run the controller
```sh
(export $(cat ./controller-config.env | xargs) && export $(cat ./aws-credentials.env | xargs) && make build-controller install run-controller)
```
5. Create a health check probe that will fail
```sh
kubectl apply -f - <<EOF                                                                                                                                                                                                          
apiVersion: kuadrant.io/v1alpha1
kind: DNSHealthCheckProbe
metadata:
name: example-probe
spec:
address: "127.0.0.1"
host: localhost
port: 3333 …
```
=> #314 Metrics for health check probe failures

hack/quickstart-setup.sh
Remove `-i` option from the tools image's `docker run` command to prevent quickstart script exiting early when piping it to bash.
Verify that curling the script and piping it to bash successfully creates and configures clusters.
```
curl https://raw.githubusercontent.com/eoinfennessy/multicluster-gateway-controller/fix_quickstart_with_curl/hack/quickstart-setup.sh | bash
```
=> Run tools image in non-interactive mode

pkg/_internal/conditions/conditions.go, pkg/_internal/conditions/conditions_test.go, pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/dnsrecord/dnsrecord_controller.go, pkg/controllers/managedzone/managedzone_controller.go, pkg/controllers/tlspolicy/tlspolicy_controller.go, test/e2e/gateway_single_spoke_test.go, test/integration/dnspolicy_controller_test.go, test/integration/tlspolicy_controller_test.go
updates to original https://github.com/Kuadrant/multicluster-gateway-controller/pull/433 
closes  #324 
- make the condition more generic so it can be used by tls policy
- ensure the condition is removed when policy is removed
- Improve the message so it gives clear pointer to which policy is affecting the gateway
**Verification**
Expected that you have setup the placement and managed clusters etc
1) Create a gateway excluding TLS for simplicity. Change to your own listener host
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
name: prod-web
namespace: multi-cluster-gateways
labels:
cluster.open-cluster-management.io/placement: http-gateway
spec:
gatewayClassName: kuadrant-multi-cluster-gateway-instance-per-cluster
listeners:
- allowedRoutes:
namespaces:
from: All …
```
=> Gh 324 policy affected condition

config/crd/bases/kuadrant.io_managedzones.yaml, config/local-setup/controller/aws/managed_zone.yaml, config/local-setup/controller/gcp/managed_zone.yaml, docs/dns-policy.md, docs/how-to/dns-provider.md, docs/how-to/managedZone.md, docs/how-to/mgc-setup.md, docs/how-to/providers/providers.md, hack/.deployUtils, pkg/apis/v1alpha1/managedzone_types.go
Add doc showing how to configure a DNS Provider for use with MZ for example. Separate doc as we will also likely want to move to using this secret directly with DNSPolicy.
Note This also removes the unused `Type` field from the MZ. It does not look to be used anywhere in the code or have any real value given the secret has the provider as part of it.
=> add doc for configuring dns provider

docs/getting-started.md, docs/how-to/ocm-control-plane-walkthrough.md
Addresses https://github.com/Kuadrant/multicluster-gateway-controller/issues/454
And also removes the addition of the step to clone the repo locally from the ocm-walkthrough due to the fact that it's used as the quickstart where we didn't want to have the need to clone the repo locally.
=> use kubectl config instead of kind context and remove need to clone repo locally 

test/integration/managedzone_controller_test.go
cc: @philbrookes @Ygnas 
Previously failing test logs:
```
ManagedZoneReconciler testing ManagedZone controller should accept a managed zone for this controller and allow deletion
/home/runner/work/multicluster-gateway-controller/multicluster-gateway-controller/test/integration/managedzone_controller_test.go:63
2023-09-06T12:08:06Z	INFO	Reconciled ManagedZone	{"managedZone": "thecat.com"}
2023-09-06T12:08:06Z	ERROR	Reconciler error	{"controller": "managedzone", "controllerGroup": "kuadrant.io", "controllerKind": "ManagedZone", "ManagedZone": {"name":"thecat.com","namespace":"default"}, "namespace": "default", "name": "thecat.com", "reconcileID": "d0e388a1-6651-489f-8df3-8c0f4b3fd9b0", "error": "Operation cannot be fulfilled on managedzones.kuadrant.io \"thecat.com\": the object has been …
```
=> flakey managedzonecontroller test fix

config/kuadrant/redis/limitador/kustomization.yaml, config/service-protection-install-guide/kustomization.yaml, config/service-protection-install-guide/managed-cluster-addon.yaml, docs/how-to/kuadrant-hub-install.md, docs/how-to/ratelimiting-shared-redis.md, docs/how-to/service-protection-setup.md
Closes: https://github.com/Kuadrant/multicluster-gateway-controller/issues/427
Added a new Kuadrant data plane components guide, detailing how to install the data-plane components with an existing OCM ManagedCluster.
Use-case: `As a cluster admin , with an existing cluster I want to use to try Kuadrant, how can I install the data-plane components into my workload/ManagedCluster cluster.`
Note: we can likely remove/drop the existing kuadrant-addon-walkthrough doc. We should replace it with a small guide on how to use the data-plane pieces.
=> data-plane components installation guide

docs/how-to/ocm-control-plane-walkthrough.md
Small format that fixes the copy of the block below which has been problematic due to formatting.
Verify it's fixed by viewing the file and using the native copy function, it should be applyable in the terminal without any editing which was not previously possible.
=> format fix

docs/experimental/skupper-poc-2-gateways-resiliency-walkthrough.md, docs/experimental/submariner-poc-hub-gateway-walkthrough.md, docs/how-to/metrics-federation.md, docs/how-to/metrics-walkthrough.md
Related to https://github.com/Kuadrant/docs.kuadrant.io/pull/12 - fixing some broken links, as mkdocs doesn't copy static assets that are in <img> tags
=> fixing some broken image links

.github/workflows/ci.yaml, bundle/manifests/kuadrant.io_dnspolicies.yaml, bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, hack/make/bundle.make, hack/make/check.make
Adds a new verify bundle command that executes `make bundle` and ensures
the contents of `./bundle` are unchanged.
Add a check for createdAt being the only change to the bundle and ignore
it. Since operator-sdk 1.26.0, `make bundle` changes the `createdAt`
field from the bundle even if there are not other changes.
see https://github.com/Kuadrant/kuadrant-operator/blob/main/Makefile#L427
Update out of date OLM bundle contents `make bundle`
=> Add verify bundle

pkg/controllers/dnspolicy/dns_helper.go, pkg/controllers/dnspolicy/dns_helper_test.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go, test/integration/dnspolicy_controller_test.go, test/integration/helper_test.go
**What**
Account for multiple listeners resulting in more than one probe associate with an ip address/hostname which was the check used to get probes for setting endpoints based on healthy check probes.
The change itself is small.
Adding some additional unit and e2e tests to cover this case as well. 
Relates to https://github.com/Kuadrant/multicluster-gateway-controller/issues/272
=> account for probes relating to multiple listeners

docs/getting-started.md
Code formatting was looking odd:
=> fixing odd formatting on getting-started.md

bundle/manifests/kuadrant.io_dnspolicies.yaml, bundle/manifests/kuadrant.io_tlspolicies.yaml, bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, config/crd/kustomization.yaml, config/crd/patches/policy-patch.yaml
> Closes #463 
Add the gateway.networking.k8s.io/policy annotation to policy CRDs
* Run `kustomize build config/crd`
* Verify that the output includes the annotation in the DNSPolicy and TLSPolicy CRDs
=> #463: Add gateway.networking.k8s.io/policy annotation

docs/dnspolicy/dns-provider.md, docs/dnspolicy/managed-zone.md
Fixes issues noted in https://github.com/Kuadrant/multicluster-gateway-controller/issues/543
* Add better DNS Provider docs, especially for GCP 
* Include a sample of how to create a dnsProviderSecretRef for AWS and GCP (perhaps covered by above)
* Formatting for spec fields seems broken e.g. - ID -> id
* Actually show how to create a ManagedZone resource (was missing)
=> Updating ManagedZone and DNS Provider docs for clarity

docs/installation/control-plane-installation.md
I can see the link is already in the prerequisites section of the guide.
However, I think it can be made clearer by changing that text to reference 'credentials' instead of a secret having to exist.
Also, a link to that same guide further down can reiterate where to get help if your struggling (like I was) to understand what the value for `${GOOGLE}` should be
=> Add link to dns provider guide

bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, config/add-on-manager/manager.yaml, config/manager/manager.yaml
#541 
**What**
On  main we build images tagged main. This is a floating tag. To ensure we always get the latest, we need to set the image pull policy to `Always`
=> set image pull policy to always

pkg/dns/google/google.go, pkg/dns/google/google_test.go
fixes #563 
Fix `toResourceRecordSets` in google dns provider to make sure that only a single record set is created for each unique dnsName. Issue was introduced here
https://github.com/Kuadrant/multicluster-gateway-controller/pull/401/commits/c57366eb6ee1123e266bdb543e598303f9ddb3a0#diff-eea59a6fb9851390f6210a03f57ba88ea1628c32d20d526998600135a1642bedR494
=> Fix google dns for records with multiple targets

docs/tlspolicy/tls-policy.md
Small docs updates around the creation of the issuer for the Let'sEncrypt setup.
Update relates to https://github.com/Kuadrant/multicluster-gateway-controller/issues/507 and https://github.com/Kuadrant/multicluster-gateway-controller/issues/568
=> docs updates

docs/tlspolicy/tls-policy.md
Update the LE Issuer example to use reference all AWS credentials from the secret. The version of cert-manager that is installed by default in local development(v1.12.2) should have these options.
=> Update tls docs

bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, config/rbac/role.yaml, pkg/controllers/tlspolicy/certmanager_helper.go, pkg/controllers/tlspolicy/tlspolicy_controller.go, test/e2e/gateway_single_spoke_test.go, test/integration/tlspolicy_controller_test.go, test/util/suite_config.go, test/util/test_types.go
Closes #581 
Verification 
Follow https://docs.kuadrant.io/getting-started/
Follow https://docs.kuadrant.io/multicluster-gateway-controller/docs/how-to/multicluster-gateways-walkthrough/ until the creation of the TLSPolicy
Create TLSPolicy pointing to ClusterIssuer with a name that doesn't exist in the cluster
Validate that error is present in the status of the TLSPolicy
```
- lastTransitionTime: "2023-09-21T10:13:13Z"
message: ClusterIssuer.cert-manager.io "blah" not found
reason: ReconciliationError
status: "False"
type: Ready
```
Create an issuer in a namespace that is different to the TLSPolicy - steps here to do that https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/tlspolicy/tls-policy.md#lets-encrypt-issuer-for-route53-hosted-domain - update the namespace …
=> validate the presence of specified issuer or clusterisssuer in tlspolicy

docs/installation/service-protection-installation.md
Updated docs with a note around CatalogSource for OpenShift installs of the Kuadrant addon
Workaround for #574
=> #574 - addon catalogsource for OpenShift installs

cmd/ocm/addon-manager/manifests/subscription.yaml, cmd/ocm/main.go
kubectl annotate managedclusteraddon kuadrant-addon "addon.open-cluster-management.io/values"='{"CatalogSource":"openshift-marketplace/community-operators", "CatalogSourceNS":"somens"}' -n local-cluster
=> allow source ns to be overridden

pkg/_internal/conditions/conditions.go, pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/tlspolicy/tlspolicy_controller.go, test/integration/dnspolicy_controller_test.go, test/integration/tlspolicy_controller_test.go
Updates the policy status (DNSPolicy and TLSPolicy) when the target resource is not found. The Ready condition is set to false with the reason "TargetNotFound" and the message is set to the appropriate error detailing the missing object.
```
{
"lastTransitionTime": "2023-09-26T17:20:17Z",
"message": "target not found : Gateway.gateway.networking.k8s.io \"prod-web-istio\" not found",
"reason": "TargetNotFound",
"status": "False",
"type": "Ready"
}
```
closes #361
=> Update policy status on TargetNotFound

bundle/manifests/kuadrant.io_dnspolicies.yaml, bundle/manifests/kuadrant.io_tlspolicies.yaml, config/crd/kustomization.yaml, config/crd/patches/policy-patch.yaml
`gateway.networking.k8s.io/policy` should be a label, rather than an annotation:
See: https://gateway-api.sigs.k8s.io/geps/gep-713/#kubectl-plugin
Noticed while checking out `gwctl` (should be able to use it after this). 
I think RLP and AuthPolicy may be missing this label.
=> gateway.networking.k8s.io/policy should be a label

cmd/controller/main.go, pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go, test/integration/dnspolicy_controller_test.go, test/integration/suite_test.go
Change in how we get information about clusters onto which we placed gateway. Instead of poking the OCM we now extract those from the GW CR itself. 
1. Follow one of the submariner PoCs up to the point where you have gateway placed on the multiple clusters 
2. Ensure that DNSRecords have endpoints set 
closes #311
=> GH-311 gateway status instead of ocm api calls

test/e2e/gateway_single_spoke_test.go, test/util/helper.go, test/util/suite_config.go, test/util/test_types.go
Addresses parts of https://github.com/Kuadrant/multicluster-gateway-controller/issues/587
Adding e2e tests to cover the e2e cases listed in the issue.
=> verify wildcard cert on http get request

bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, cmd/controller/main.go, config/quick-start/control-cluster/cluster-config/configmap.yaml, config/rbac/role.yaml, pkg/_internal/slice/predicates.go, pkg/_internal/slice/slice.go, pkg/controllers/gateway/gateway_controller.go, pkg/controllers/gateway/params.go, pkg/policysync/eventhandler.go, pkg/policysync/policy.go, pkg/policysync/policy_test.go, pkg/policysync/reflect.go, pkg/policysync/runnable.go, pkg/policysync/syncer.go, pkg/policysync/unstructured.go
Add new `policiesToSync` field to the GatewayClass parameters, which allows users to specify GVRs of policies to watch
Currently the watch only adds a log message when an event is triggered
1. Start the development environment
2. Apply the ConfigMap with the updated parameters to watch AuthPolicies:
```sh
kubectl apply -f config/quick-start/control-cluster/cluster-config/configmap.yaml
```
3. Edit the GatewayClass to reference the parameters
```sh
kubectl edit gatewayclass kuadrant-multi-cluster-gateway-instance-per-cluster -o yaml
```
```yaml
spec:
controllerName: kuadrant.io/mgc-gw-controller
parametersRef:
group: ""
kind: ConfigMap
name: gateway-params
namespace: multi-cluster-gateways
```
4. Ensure the AuthPolicies CRD is installed
```sh
kubectl apply -f …
```
=> Watch policies configured by Gateway params

config/prometheus-for-federation/ocp_monitoring/.gitignore, config/prometheus-for-federation/ocp_monitoring/README.md, config/prometheus-for-federation/ocp_monitoring/grafana_datasources.yaml.template, config/prometheus-for-federation/ocp_monitoring/kustomization.yaml, config/prometheus-for-federation/ocp_monitoring/monitoring.yaml
Requires an OSD or OCP cluster to verify.
Adds all metrics to the user-workload-monitoring in ocp, and a grafana instance with all available dashboards.
=> Add ocp_monitoring sub dir to prometheus-for-federation config

pkg/controllers/dnspolicy/dns_helper.go, pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks.go, pkg/controllers/dnspolicy/dnspolicy_healthchecks_test.go, pkg/controllers/tlspolicy/tlspolicy_certmanager_certificates.go, pkg/controllers/tlspolicy/tlspolicy_controller.go, test/integration/dnspolicy_controller_test.go, test/integration/tlspolicy_controller_test.go
Addressed #628  
Follow the steps described in the issue, the dnsrecord should be deleted.
kubectl create secret generic probe-headers --from-literal=test=dGVzdAo= -n multi-cluster-gateways
Follow the steps describe in the issue with the following adjustments. 
Add the following block to your dnspolicy
```
healthCheck:
additionalHeadersRef:
name: probe-headers
allowInsecureCertificates: true
endpoint: /
expectedResponses:
- 200
- 201
- 301
failureThreshold: 1
port: 443
protocol: https
```
there should be one dnshealthcheck probe present in the cluster now
e.g.
```
kc get dnshealthcheckprobes -A        
NAMESPACE                NAME                        HEALTHY   LAST CHECKED
multi-cluster-gateways   172.31.200.0-prod-web-api   true      3s
```
Delete the dnspolicy, the healthcheck probe …
=> gh-628 fix deletion of dnsrecord and certificates on deletion of gateway target for dnspolicy and tlspolicy

pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/tlspolicy/tlspolicy_certmanager_certificates.go
Remove duplicate assignment of gatewayDiffObj
Remove alwaysUpdateCertificate mutate function (Come back to this, we should be trying to use this pattern in all our policies, not removing it.)
Introduced in https://github.com/Kuadrant/multicluster-gateway-controller/pull/635, really not sure why they weren't picked up in the PR CI job
=> Fix lint errors

bundle/manifests/kuadrant.io_dnspolicies.yaml, bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, config/policy-controller/crd/bases/kuadrant.io_dnspolicies.yaml, go.mod, pkg/apis/v1alpha1/dnspolicy_types.go, pkg/controllers/dnspolicy/dns_helper.go, pkg/controllers/dnspolicy/dns_helper_test.go, pkg/controllers/dnspolicy/dnspolicy_controller.go, pkg/controllers/dnspolicy/dnspolicy_dnsrecords.go, test/e2e/gateway_single_spoke_test.go, test/policy_integration/dnspolicy_controller_test.go, test/policy_integration/helper_test.go, test/policy_integration/tlspolicy_controller_test.go, test/util/test_dnspolicy_types.go, test/util/test_types.go
Adds a routing strategy field to the DNSPolicy spec that determines how the policy with generate endpoints for any created DNSRecords.
Two routing strategies are allowed, `simple` and `loadbalanced`. Simple will creates a single DNS record (A or CNAME) for each listener/hostname with all ip/hostnames as targets. LoadBalanced works as before by creating a more complex record structure with CNAMES and A records using Geo and Weighted routing strategies to achieve loadbalancing functionality.
The strategy field is currently marked as immutable and it should not be changed after initial DNSPolicy creation.
closes #655
=> Add DNSPolicy Routing Strategy

config/prometheus/gateway-controller-service.yaml, config/prometheus/policy-controller-service.yaml
This  #648 PR introduced the policy controller metrics service and the quickstart-metrics script failed because it could not merge it with the previous service as they had the same name.
Both quickstart-setup and quickstart-metrics still work.
=> Renamed metric services

bundle/manifests/multicluster-gateway-controller.clusterserviceversion.yaml, config/add-on-manager/manager.yaml, config/policy-controller/rbac/role.yaml, hack/make/policy_controller.make, pkg/controllers/tlspolicy/tlspolicy_controller.go, test/e2e/gateway_single_spoke_test.go
fix `pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.ClusterIssuer: unknown (get clusterissuers.cert-manager.io)`
=> fix perms around issuers

test/gateway_integration/suite_test.go, test/policy_integration/dnspolicy_controller_health_checks_test.go, test/policy_integration/dnspolicy_controller_multi_cluster_test.go, test/policy_integration/dnspolicy_controller_single_cluster_test.go, test/policy_integration/dnspolicy_controller_test.go, test/policy_integration/suite_test.go, test/policy_integration/tlspolicy_controller_test.go
Created separate files for dnspolicy controller tests:
dnspolicy_controller_test.go - DNSPolicy common lifecycle tests
dnspolicy_controller_health_checks_test.go - DNSPolicy Health check specific tests
dnspolicy_controller_multi_cluster_test.go - DNSPolicy Multi Cluster (Gateway with MGC status address) specific tests
dnspolicy_controller_single_cluster_test.go - DNSPolicy Single Cluster (Gateway with standard status address) specific tests
=> Split dnspolicy tests

pkg/apis/v1alpha1/tlspolicy_types.go, test/e2e/gateway_single_spoke_test.go, test/util/helper.go, test/util/test_types.go
$subject
As discussed here -> https://kubernetes.slack.com/archives/C05J0D0V525/p1699520931987239
=> remove http check for wildcard certificate in favour of checking certificates

docs/reference/dnspolicy.md, docs/reference/tlspolicy.md
Adds API reference docs for the DNSPolicy and TLSPolicy. Follows the same layout as kuadrant-operator policies
(https://github.com/Kuadrant/kuadrant-operator/tree/main/doc/reference)
part of #670
part of #627
=> docs: Add API reference docs for policies

config/mgc-install-guide/delete-cluster-issuer.yaml, config/mgc-install-guide/kustomization.yaml, docs/installation/control-plane-installation.md, docs/installation/service-protection-installation.md
Fix issue in docs with no add-ons enabled via ocm
Fix issue with glbc ClusterIssuer being installed
Fix issue with install check not looking at policy controller
Fix Gateway API version
Add Context to hub commands - after ocm quickstart the context is set to the last spoke cluster.
Remove one of the options for adding the `RawFeedbackJsonString` - option 1 was problematic on mac. also if the user follows https://open-cluster-management.io/getting-started/quick-start/ some of the steps that were in option 1 were done by the installer. 
Move the installation of the cert-manager step above (optional with the removal of the issuer during installation)
Improve the flow of creating the ManagedZone section/commands
=> Install guide updates

docs/dnspolicy/dns-health-checks.md, docs/dnspolicy/dnspolicy-quickstart.md, docs/dnspolicy/dnspolicy.md, docs/how-to/multicluster-loadbalanced-dnspolicy.md
* Created a dnspolicy overview doc docs/dnspolicy/dnspolicy.md based on the structure of other kuadrant overview docs. 
*  Moved current dnspolicy doc to docs/how-to/multicluster-loadbalanced-dnspolicy.md (This needs a follow on to convert it correctly to a how to guide). What is in this doc currently is kind of a mix of a guide and reference.
closes #670
=> docs: Add DNSPolicy overview doc

hack/.quickstartEnv
**Summary**
Fixing the wording used in the quickstart prompts for AWS credentials. Current wording causes confusion as the term `secret` is used for both the access key and secret key
=> Fixing prompt text when asking for AWS credentials

hack/.deployUtils
Fix for ManagedZone status during local setup/quickstart
```
message: 'The DNS provider failed to ensure the managed zone: Secret "mgc-aws-credentials"
not found'
```
=> Fix dns provider secret namespace to match ManagedZone namespace

config/samples/kustomization.yaml
This PR is related to: [kuadrant-operator/pull/372](https://github.com/Kuadrant/kuadrant-operator/pull/372)
Adds a kustomization.yaml containing a reference to a set of yaml samples.
To be used as a remote kustomize base in the kuadrant-operator.
The main purpose of this is to have the YAML samples for TLSPolicy, DNSPolicy and ManagedZone displayed in the Operator Hub for kuadrant-operator.
Follow up on the discussion [here](https://github.com/Kuadrant/kuadrant-operator/pull/372/files/b99f99eca66980e61653d4fc7bb48d0242d56544#r1423749325).
No effect on MGC.
=> Add config/samples/kustomization.yaml

docs/installation/service-protection-installation.md
fixes https://github.com/Kuadrant/kuadrant-operator/issues/269
=> add example to override channel

docs/how-to/multicluster-gateways-walkthrough.md, docs/how-to/simple-ratelimitpolicy-for-app-developers.md, docs/installation/control-plane-installation.md, hack/.deployUtils, hack/.kindUtils, hack/.quickstartEnv, hack/.setupEnv
To be able to re-use some of the functions in the quickstart script for kuadrant-operator I've tried to make them a little more generic:
- Made the network in `dockerBinCmd` overridable by env var instead of set to mgc
- Made the namespace for `configureController` overridable
- Renamed quite a few environment variables to `KUADRANT_` instead of `MGC_`
=> Make some scripts more generic

config/prometheus-for-federation/api-dashboards/gatekeeper_dashboard.json, config/prometheus-for-federation/api-dashboards/grafana_deployment_patch.yaml, config/prometheus-for-federation/api-dashboards/kustomization.yaml, config/prometheus-for-federation/api-dashboards/stitch.json, config/prometheus-for-federation/api-dashboards/stitch_platform_eng_dashboard.json, config/prometheus-for-federation/kustomization.yaml, hack/.deployUtils, hack/upstream-api/local-setup-mgc-api.sh
Closes #744 
Closes #745 
The first commit is a bugfix for something I noticed when making changes. A patch to the number of alertmanager replicas wasn't being applied.
The 2nd commit installs the prometheus, thanos, grafana, kube-state-metrics stack, in the same manner as how it is installed for the mgc metrics quickstart. This sets up metric collection from the components we want (istio, istiod, envoy), and federates the metrics back to thanos in the hub. It also installs some grafana dashboards for mgc use (which are not relevant to stitch api) and some stitch api specific dashboards (imported from the stitch poc private repo).
No data will show up on the new dashboard unless an app is configured in the istio gateway. 
Therefore it's sufficient to just see the 3 stitch dashboards show …
=> Add stitch dashboards

.github/workflows/ci-e2e.yaml, hack/.deployUtils, test/e2e/gateway_single_spoke_test.go
Don't configure managed addon when OCM_SINGLE is being used. 
**Note:** OCM_SINGLE shouldn't really be used anywhere now but our e2e tests currently still rely on it.
Changes added to allow errors to be surfaced when checking the dnsrecord resource status.
=> fix: GCP e2e tests

.github/workflows/ci.yaml
Updates to remove lint errors and other warnings.
actions/checkout@v2 -> actions/checkout@v4
- Removes warnings about node versions
golangci/golangci-lint-action@v2 -> golangci/golangci-lint-action@v3
- golangci v1.53.3 -> v1.55.2
actions/setup-go@v2 -> actions/setup-go@v4
- remove skip-go-installation, Deprecated
- Disable cache, enabled by default since v4 https://github.com/actions/setup-go/releases/tag/v4.0.0
These changes should hopefully get rid of all the errors and warnings you can see here https://github.com/Kuadrant/multicluster-gateway-controller/actions/runs/7554224075, and also make lint work again on main (maybe :-/).
=> Update CI GH workflow

config/prometheus-for-federation/kustomization.yaml
If following the metrics quickstart, alertmanager runs with 3 replicas.
This change fixes a patch so that only 1 replica runs (which was the expected behaviour when originally added)
@R-Lawton This makes sense to cherry-pick from #756 back to main as well.
=> Fix Alertmanager name so patch gets applied

config/quick-start/control-cluster/cluster-config/configmap.yaml, pkg/controllers/gateway/params.go
Rename `policiesToSync` => `experimentalPolicySync` field in GatewayClass params
=> Rename policiesToSync GatewayClass param field

README.md, docs/managed-zone.md
Ref: https://github.com/Kuadrant/docs.kuadrant.io/issues/56
=> [docs] Fixing some broken links

docs/how-to/multicluster-gateways-walkthrough.md, hack/quickstart-cleanup.sh
Small updates to Multicluster Gateways Walkthroughs
Quickstart cleanup fix - the `cleanup` function no longer exists
=> Walkthrough text updates and quickstart cleanup fix

.github/workflows/controller-image.yaml
Install correct golang version (1.21.x)
Related to https://github.com/Kuadrant/multicluster-gateway-controller/pull/785
Test run here https://github.com/Kuadrant/multicluster-gateway-controller/actions/runs/7990993383
=> fix: ci bundle image build

config/prometheus-for-federation/ksm_clusterrole_patch.yaml
This has been already applied to the api-upstream branch [here](https://github.com/Kuadrant/multicluster-gateway-controller/commit/b9f53406c94827fecaeac263796afac857660509), which is needed & referenced by the api-quickstart repo.
However, it should land back on main here as well.
=> Add kaudrant resources to ksm permissions
